# Problema [76](https://projecteuler.net/problem=76)

In [1]:
import datetime as dt
from itertools import combinations_with_replacement
import numpy as np

In [2]:
INICIO = dt.datetime.now()
for N in range(2, 15):
    a = list(range(N))
    contador = len([1 for t in combinations_with_replacement(a, N) if t[0] == 0 and sum(t) == N]) + 1
    instante = str(dt.datetime.now() - INICIO)
    print(N, "\t", contador, '\t', instante)

2 	 1 	 0:00:00.000148
3 	 2 	 0:00:00.000745
4 	 4 	 0:00:00.000885
5 	 6 	 0:00:00.001041
6 	 10 	 0:00:00.001312
7 	 14 	 0:00:00.001941
8 	 21 	 0:00:00.003502
9 	 29 	 0:00:00.009188
10 	 41 	 0:00:00.030990
11 	 55 	 0:00:00.122094
12 	 76 	 0:00:00.447642
13 	 100 	 0:00:01.716649
14 	 134 	 0:00:06.686558


**referencias**:  
- https://oeis.org/A000065  
- http://verso.mat.uam.es/~pablo.fernandez/entrega3-EDEM-MD16-17.pdf

In [3]:
N = 10
p = np.array([[0]*N]*N)
for i in range(1, N):
    p[i][1] = 1
#p[1][1] = 1
p

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
for n in range(2, N):
    for k in range(2, n+1):
        v1 = p[n-1][k-1]
        v2 = p[n-k][k]
        print(f'p[{n}][{k}] = p[{n-1}][{k-1}] ({v1}) + p[{n-k}][{k}] ({v2})')
        p[n][k] = v1 + v2 
    print("")
p

p[2][2] = p[1][1] (1) + p[0][2] (0)

p[3][2] = p[2][1] (1) + p[1][2] (0)
p[3][3] = p[2][2] (1) + p[0][3] (0)

p[4][2] = p[3][1] (1) + p[2][2] (1)
p[4][3] = p[3][2] (1) + p[1][3] (0)
p[4][4] = p[3][3] (1) + p[0][4] (0)

p[5][2] = p[4][1] (1) + p[3][2] (1)
p[5][3] = p[4][2] (2) + p[2][3] (0)
p[5][4] = p[4][3] (1) + p[1][4] (0)
p[5][5] = p[4][4] (1) + p[0][5] (0)

p[6][2] = p[5][1] (1) + p[4][2] (2)
p[6][3] = p[5][2] (2) + p[3][3] (1)
p[6][4] = p[5][3] (2) + p[2][4] (0)
p[6][5] = p[5][4] (1) + p[1][5] (0)
p[6][6] = p[5][5] (1) + p[0][6] (0)

p[7][2] = p[6][1] (1) + p[5][2] (2)
p[7][3] = p[6][2] (3) + p[4][3] (1)
p[7][4] = p[6][3] (3) + p[3][4] (0)
p[7][5] = p[6][4] (2) + p[2][5] (0)
p[7][6] = p[6][5] (1) + p[1][6] (0)
p[7][7] = p[6][6] (1) + p[0][7] (0)

p[8][2] = p[7][1] (1) + p[6][2] (3)
p[8][3] = p[7][2] (3) + p[5][3] (2)
p[8][4] = p[7][3] (4) + p[4][4] (1)
p[8][5] = p[7][4] (3) + p[3][5] (0)
p[8][6] = p[7][5] (2) + p[2][6] (0)
p[8][7] = p[7][6] (1) + p[1][7] (0)
p[8][8] = p[7][7] (1) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 2, 2, 1, 1, 0, 0, 0, 0],
       [0, 1, 3, 3, 2, 1, 1, 0, 0, 0],
       [0, 1, 3, 4, 3, 2, 1, 1, 0, 0],
       [0, 1, 4, 5, 5, 3, 2, 1, 1, 0],
       [0, 1, 4, 7, 6, 5, 3, 2, 1, 1]])

In [5]:
for fila in p:
    print(fila, np.sum(fila))

[0 0 0 0 0 0 0 0 0 0] 0
[0 1 0 0 0 0 0 0 0 0] 1
[0 1 1 0 0 0 0 0 0 0] 2
[0 1 1 1 0 0 0 0 0 0] 3
[0 1 2 1 1 0 0 0 0 0] 5
[0 1 2 2 1 1 0 0 0 0] 7
[0 1 3 3 2 1 1 0 0 0] 11
[0 1 3 4 3 2 1 1 0 0] 15
[0 1 4 5 5 3 2 1 1 0] 22
[0 1 4 7 6 5 3 2 1 1] 30


In [6]:
N = 100
N += 1
p = np.array([[0]*N]*N)
for i in range(1, N):
    p[i][1] = 1
for n in range(2, N):
    #n += 1
    for k in range(2, n+1):
        #k += 1
        v1 = p[n-1][k-1]
        v2 = p[n-k][k]
        #print(f'p[{n}][{k}] = p[{n-1}][{k-1}] ({v1}) + p[{n-k}][{k}] ({v2})')
        p[n][k] = v1 + v2 
    #print("")
m = [(ene, np.sum(fila)-1) for ene, fila in enumerate(p)]
m

[(0, -1),
 (1, 0),
 (2, 1),
 (3, 2),
 (4, 4),
 (5, 6),
 (6, 10),
 (7, 14),
 (8, 21),
 (9, 29),
 (10, 41),
 (11, 55),
 (12, 76),
 (13, 100),
 (14, 134),
 (15, 175),
 (16, 230),
 (17, 296),
 (18, 384),
 (19, 489),
 (20, 626),
 (21, 791),
 (22, 1001),
 (23, 1254),
 (24, 1574),
 (25, 1957),
 (26, 2435),
 (27, 3009),
 (28, 3717),
 (29, 4564),
 (30, 5603),
 (31, 6841),
 (32, 8348),
 (33, 10142),
 (34, 12309),
 (35, 14882),
 (36, 17976),
 (37, 21636),
 (38, 26014),
 (39, 31184),
 (40, 37337),
 (41, 44582),
 (42, 53173),
 (43, 63260),
 (44, 75174),
 (45, 89133),
 (46, 105557),
 (47, 124753),
 (48, 147272),
 (49, 173524),
 (50, 204225),
 (51, 239942),
 (52, 281588),
 (53, 329930),
 (54, 386154),
 (55, 451275),
 (56, 526822),
 (57, 614153),
 (58, 715219),
 (59, 831819),
 (60, 966466),
 (61, 1121504),
 (62, 1300155),
 (63, 1505498),
 (64, 1741629),
 (65, 2012557),
 (66, 2323519),
 (67, 2679688),
 (68, 3087734),
 (69, 3554344),
 (70, 4087967),
 (71, 4697204),
 (72, 5392782),
 (73, 6185688),
 (74, 

In [7]:
m[N-1][1]

190569291